  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync fork with upstream
        run: |
          git remote add upstream https://github.com/TypingMind/typingmind.git
          git fetch upstream
          git checkout main
          git reset --hard upstream/main  # Force match upstream
          git push origin main --force    # Force push to your fork
